create table if not exists public.rooms (
  slug text primary key check (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$'),
  name text not null,
  created_at timestamptz not null default now()
);

insert into public.rooms (slug, name)
values ('main', 'Main')
on conflict (slug) do nothing;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  body text not null check (char_length(body) <= 220),
  author text not null default 'Anonymous' check (char_length(author) <= 28),
  topic text not null default 'Audience',
  room_slug text not null default 'main' references public.rooms(slug) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  answered_at timestamptz
);

alter table public.questions
add column if not exists room_slug text not null default 'main';

alter table public.questions
drop constraint if exists questions_room_slug_fkey;

alter table public.questions
add constraint questions_room_slug_fkey
foreign key (room_slug) references public.rooms(slug) on delete cascade;

alter table public.questions
add column if not exists user_id uuid references auth.users(id) on delete set null;

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  client_id text,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (question_id, client_id)
);

alter table public.votes
alter column client_id drop not null;

alter table public.votes
add column if not exists user_id uuid references auth.users(id) on delete cascade;

create unique index if not exists votes_question_user_id_key
on public.votes (question_id, user_id)
where user_id is not null;

create table if not exists public.moderators (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.questions enable row level security;
alter table public.votes enable row level security;
alter table public.moderators enable row level security;
alter table public.rooms enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.rooms to anon, authenticated;
grant insert, update on public.rooms to anon, authenticated;
grant select on public.questions to anon, authenticated;
grant insert, update on public.questions to authenticated;
grant select on public.votes to anon, authenticated;
grant insert, delete on public.votes to authenticated;
grant select on public.moderators to authenticated;

drop policy if exists "Anyone can read rooms" on public.rooms;
drop policy if exists "Signed in users can create rooms" on public.rooms;
drop policy if exists "Signed in users can update rooms" on public.rooms;

create policy "Anyone can read rooms"
on public.rooms for select
to anon, authenticated
using (true);

create policy "Signed in users can create rooms"
on public.rooms for insert
to anon, authenticated
with check (true);

create policy "Signed in users can update rooms"
on public.rooms for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Anyone can read questions" on public.questions;
drop policy if exists "Anyone can create questions" on public.questions;
drop policy if exists "Anyone can update answered state" on public.questions;
drop policy if exists "Signed in users can create questions" on public.questions;
drop policy if exists "Moderators can update questions" on public.questions;

create policy "Anyone can read questions"
on public.questions for select
to anon, authenticated
using (true);

create policy "Signed in users can create questions"
on public.questions for insert
to authenticated
with check (user_id = auth.uid());

create policy "Moderators can update questions"
on public.questions for update
to authenticated
using (
  exists (
    select 1
    from public.moderators
    where moderators.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.moderators
    where moderators.user_id = auth.uid()
  )
);

drop policy if exists "Anyone can read votes" on public.votes;
drop policy if exists "Anyone can create votes" on public.votes;
drop policy if exists "Anyone can remove their vote" on public.votes;
drop policy if exists "Anyone can create votes" on public.votes;
drop policy if exists "Signed in users can vote" on public.votes;
drop policy if exists "Signed in users can remove their vote" on public.votes;

create policy "Anyone can read votes"
on public.votes for select
to anon, authenticated
using (true);

create policy "Signed in users can vote"
on public.votes for insert
to authenticated
with check (user_id = auth.uid());

create policy "Signed in users can remove their vote"
on public.votes for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can read their own moderator role" on public.moderators;
create policy "Users can read their own moderator role"
on public.moderators for select
to authenticated
using (user_id = auth.uid());

do $$
begin
  alter publication supabase_realtime add table public.rooms;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.questions;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.votes;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.moderators;
exception
  when duplicate_object then null;
end $$;

-- After a presenter signs up, make them a moderator from the SQL Editor:
-- insert into public.moderators (user_id)
-- select id from auth.users where email = 'presenter@example.com';
