create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  body text not null check (char_length(body) <= 220),
  author text not null default 'Anonymous' check (char_length(author) <= 28),
  topic text not null default 'Audience',
  created_at timestamptz not null default now(),
  answered_at timestamptz
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  client_id text not null,
  created_at timestamptz not null default now(),
  unique (question_id, client_id)
);

alter table public.questions enable row level security;
alter table public.votes enable row level security;

grant usage on schema public to anon;
grant select, insert, update on public.questions to anon;
grant select, insert, delete on public.votes to anon;

drop policy if exists "Anyone can read questions" on public.questions;
create policy "Anyone can read questions"
on public.questions for select
to anon
using (true);

drop policy if exists "Anyone can create questions" on public.questions;
create policy "Anyone can create questions"
on public.questions for insert
to anon
with check (true);

drop policy if exists "Anyone can update answered state" on public.questions;
create policy "Anyone can update answered state"
on public.questions for update
to anon
using (true)
with check (true);

drop policy if exists "Anyone can read votes" on public.votes;
create policy "Anyone can read votes"
on public.votes for select
to anon
using (true);

drop policy if exists "Anyone can create votes" on public.votes;
create policy "Anyone can create votes"
on public.votes for insert
to anon
with check (true);

drop policy if exists "Anyone can remove their vote" on public.votes;
create policy "Anyone can remove their vote"
on public.votes for delete
to anon
using (true);

do $$
begin
  alter publication supabase_realtime add table public.questions;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.votes;
exception
  when duplicate_object then null;
end $$;
